#!/usr/bin/env python

import click
import requests

@click.group()
def cli():
    pass

@click.command()
def list():
    click.echo('List of archives')
    resp = requests.get(
        url="https://api.restorehub.co/repositories/content/archives"
    )

    # initial values
    archLen = len(resp.json()['data'])
    i = 0

    # list all archives
    if archLen > 0:
        for arch in resp.json()['data']:
            i = i+1
            click.echo('{}. {}'.format(i, arch['name']))
    else:
        click.echo('Empty repository')


@click.command()
@click.option('--archive', help='the archive to push')
@click.option('--destination', help='an archive will be pushed to the destination')
def push(archive, destination):
    click.echo('Data snapshot {} is pushed to {}'.format(archive, destination))

cli.add_command(list)
cli.add_command(push)

if __name__ == '__main__':
    cli()
